server:
  port: 9001
spring:
  application:
    name: tensquare-base
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.205.128:3306/tensquare_base?characterEncoding=utf-8&amp;useSSL=true
